#!/bin/bash

# AETHER Bot - Railway Deployment Script

echo "🚀 Deploying AETHER Bot to Railway..."
echo ""
echo "📌 Instrukcja:"
echo "1. Wejdź na https://railway.app"
echo "2. Zaloguj się przez GitHub"
echo "3. Kliknij 'New Project'"
echo "4. Wybierz 'Deploy from GitHub repo'"
echo "5. Wybierz repo: aether-bot"
echo ""
echo "📌 Zmienne środowiskowe do dodania:"
echo "====================================="
echo "TELEGRAM_BOT_TOKEN=8997846562:AAEaockXk3JtSQTHHCbedJz9c8-UlKzmkfA"
echo "DATABASE_PATH=/app/data/aether.json"
echo "MINING_RATE=1"
echo "MINING_INTERVAL_HOURS=4"
echo "MAX_OFFLINE_HOURS=8"
echo "OLLAMA_HOST=http://localhost:11434"
echo "DEFAULT_MODEL=gemma2"
echo "REFERRAL_BONUS=0.1"
echo "REFERRAL_BONUS_MINING=0.05"
echo "DAILY_AI_TASKS=10"
echo "MAX_CLAN_SIZE=50"
echo "====================================="
echo ""
echo "📌 Po dodaniu zmiennych, Railway automatycznie wdroży bota."
echo "📌 Bot będzie działał 24/7 na darmowym tierze ($5/mies)."
echo ""
echo "🔗 Repo: https://github.com/gromek1991-tech/aether-bot"
echo "🔗 Railway: https://railway.app"
